### Ejercicio1_BigDataMatemáticas

#### 1. Una tienda online quiere predecir la puntuación que cada usuario daría a un producto.

        Matriz de usuarios    U → cuánto les gusta cada característica de los productos.
        
        Matriz de productos   P → puntuación de cada característica de cada producto.
        
        #### Matriz de usuarios (filas=usuarios, columnas=características)
        U = np.array([
            [5, 3, 1],  # Usuario 1
            [2, 4, 5],  # Usuario 2
            [3, 5, 2]   # Usuario 3
        ])
        
        ##### Matriz de productos (filas=características, columnas=productos)
        P = np.array([
            [1, 0, 2],  # Característica 1
            [0, 1, 1],  # Característica 2
            [1, 2, 0]   # Característica 3
        ]) 
        
        Calcula El producto de matrices U×P que nos da una predicción de puntuaciones. Intenta explicar el resultado

In [3]:
import numpy as np

U = np.array([
            [5, 3, 1], 
            [2, 4, 5],  
            [3, 5, 2]   
        ])
        
P = np.array([
            [1, 0, 2],  
            [0, 1, 1],  
            [1, 2, 0] 
        ]) 
C = np.dot(U,P)  # producto matricial
print('Producto matricial (predicción de puntuaciones):\n', C)

Producto matricial (predicción de puntuaciones):
 [[ 6  5 13]
 [ 7 14  8]
 [ 5  9 11]]


### Este programa no muestra el producto de las matrices U * P, es decir, la predicción de puntuaciones.